name: recode
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - torchaudio==0.9.1
  - cudatoolkit=10.2
  - pytorch==1.9.1
  - torchvision==0.10.1
  - wandb
  - tqdm
  - matplotlib
  - pandas